services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - 8080:8080

    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ./data/webui:/app/backend/data
      - ./data/ollama/ollama:/root/.ollama
    restart: unless-stopped
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              device_ids:
                - nvidia.com/gpu=all
    ports:
      - 11434:11434/tcp
    volumes:
      - ./data/ollama/ollama:/root/.ollama
